/**
 * This file is a part of ThetaRush.
 *
 * ThetaRush is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ThetaRush is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.
 *
 * If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#define DEF_GPIOA (0)
#define DEF_GPIOB (1)
#define DEF_GPIOC (2)
#define DEF_GPIOD (3)
#define DEF_GPIOE (4)
#define DEF_GPIOF (5)
#define DEF_GPIOG (6)
#define DEF_GPIOH (7)
#define DEF_GPIOI (8)
#define DEF_GPIOJ (9)
#define DEF_GPIOK (10)

#define DEFIO_TAG_E__PA0 DEFIO_TAG (A, 0)
#define DEFIO_TAG_E__PA1 DEFIO_TAG (A, 1)
#define DEFIO_TAG_E__PA2 DEFIO_TAG (A, 2)
#define DEFIO_TAG_E__PA3 DEFIO_TAG (A, 3)
#define DEFIO_TAG_E__PA4 DEFIO_TAG (A, 4)
#define DEFIO_TAG_E__PA5 DEFIO_TAG (A, 5)
#define DEFIO_TAG_E__PA6 DEFIO_TAG (A, 6)
#define DEFIO_TAG_E__PA7 DEFIO_TAG (A, 7)
#define DEFIO_TAG_E__PA8 DEFIO_TAG (A, 8)
#define DEFIO_TAG_E__PA9 DEFIO_TAG (A, 9)
#define DEFIO_TAG_E__PA10 DEFIO_TAG (A, 10)
#define DEFIO_TAG_E__PA11 DEFIO_TAG (A, 11)
#define DEFIO_TAG_E__PA12 DEFIO_TAG (A, 12)
#define DEFIO_TAG_E__PA13 DEFIO_TAG (A, 13)
#define DEFIO_TAG_E__PA14 DEFIO_TAG (A, 14)
#define DEFIO_TAG_E__PA15 DEFIO_TAG (A, 15)

#define DEFIO_TAG_E__PB0 DEFIO_TAG (B, 0)
#define DEFIO_TAG_E__PB1 DEFIO_TAG (B, 1)
#define DEFIO_TAG_E__PB2 DEFIO_TAG (B, 2)
#define DEFIO_TAG_E__PB3 DEFIO_TAG (B, 3)
#define DEFIO_TAG_E__PB4 DEFIO_TAG (B, 4)
#define DEFIO_TAG_E__PB5 DEFIO_TAG (B, 5)
#define DEFIO_TAG_E__PB6 DEFIO_TAG (B, 6)
#define DEFIO_TAG_E__PB7 DEFIO_TAG (B, 7)
#define DEFIO_TAG_E__PB8 DEFIO_TAG (B, 8)
#define DEFIO_TAG_E__PB9 DEFIO_TAG (B, 9)
#define DEFIO_TAG_E__PB10 DEFIO_TAG (B, 10)
#define DEFIO_TAG_E__PB11 DEFIO_TAG (B, 11)
#define DEFIO_TAG_E__PB12 DEFIO_TAG (B, 12)
#define DEFIO_TAG_E__PB13 DEFIO_TAG (B, 13)
#define DEFIO_TAG_E__PB14 DEFIO_TAG (B, 14)
#define DEFIO_TAG_E__PB15 DEFIO_TAG (B, 15)

#define DEFIO_TAG_E__PC0 DEFIO_TAG (C, 0)
#define DEFIO_TAG_E__PC1 DEFIO_TAG (C, 1)
#define DEFIO_TAG_E__PC2 DEFIO_TAG (C, 2)
#define DEFIO_TAG_E__PC3 DEFIO_TAG (C, 3)
#define DEFIO_TAG_E__PC4 DEFIO_TAG (C, 4)
#define DEFIO_TAG_E__PC5 DEFIO_TAG (C, 5)
#define DEFIO_TAG_E__PC6 DEFIO_TAG (C, 6)
#define DEFIO_TAG_E__PC7 DEFIO_TAG (C, 7)
#define DEFIO_TAG_E__PC8 DEFIO_TAG (C, 8)
#define DEFIO_TAG_E__PC9 DEFIO_TAG (C, 9)
#define DEFIO_TAG_E__PC10 DEFIO_TAG (C, 10)
#define DEFIO_TAG_E__PC11 DEFIO_TAG (C, 11)
#define DEFIO_TAG_E__PC12 DEFIO_TAG (C, 12)
#define DEFIO_TAG_E__PC13 DEFIO_TAG (C, 13)
#define DEFIO_TAG_E__PC14 DEFIO_TAG (C, 14)
#define DEFIO_TAG_E__PC15 DEFIO_TAG (C, 15)

#define DEFIO_TAG_E__PD0 DEFIO_TAG (D, 0)
#define DEFIO_TAG_E__PD1 DEFIO_TAG (D, 1)
#define DEFIO_TAG_E__PD2 DEFIO_TAG (D, 2)
#define DEFIO_TAG_E__PD3 DEFIO_TAG (D, 3)
#define DEFIO_TAG_E__PD4 DEFIO_TAG (D, 4)
#define DEFIO_TAG_E__PD5 DEFIO_TAG (D, 5)
#define DEFIO_TAG_E__PD6 DEFIO_TAG (D, 6)
#define DEFIO_TAG_E__PD7 DEFIO_TAG (D, 7)
#define DEFIO_TAG_E__PD8 DEFIO_TAG (D, 8)
#define DEFIO_TAG_E__PD9 DEFIO_TAG (D, 9)
#define DEFIO_TAG_E__PD10 DEFIO_TAG (D, 10)
#define DEFIO_TAG_E__PD11 DEFIO_TAG (D, 11)
#define DEFIO_TAG_E__PD12 DEFIO_TAG (D, 12)
#define DEFIO_TAG_E__PD13 DEFIO_TAG (D, 13)
#define DEFIO_TAG_E__PD14 DEFIO_TAG (D, 14)
#define DEFIO_TAG_E__PD15 DEFIO_TAG (D, 15)

#define DEFIO_TAG_E__PE0 DEFIO_TAG (E, 0)
#define DEFIO_TAG_E__PE1 DEFIO_TAG (E, 1)
#define DEFIO_TAG_E__PE2 DEFIO_TAG (E, 2)
#define DEFIO_TAG_E__PE3 DEFIO_TAG (E, 3)
#define DEFIO_TAG_E__PE4 DEFIO_TAG (E, 4)
#define DEFIO_TAG_E__PE5 DEFIO_TAG (E, 5)
#define DEFIO_TAG_E__PE6 DEFIO_TAG (E, 6)
#define DEFIO_TAG_E__PE7 DEFIO_TAG (E, 7)
#define DEFIO_TAG_E__PE8 DEFIO_TAG (E, 8)
#define DEFIO_TAG_E__PE9 DEFIO_TAG (E, 9)
#define DEFIO_TAG_E__PE10 DEFIO_TAG (E, 10)
#define DEFIO_TAG_E__PE11 DEFIO_TAG (E, 11)
#define DEFIO_TAG_E__PE12 DEFIO_TAG (E, 12)
#define DEFIO_TAG_E__PE13 DEFIO_TAG (E, 13)
#define DEFIO_TAG_E__PE14 DEFIO_TAG (E, 14)
#define DEFIO_TAG_E__PE15 DEFIO_TAG (E, 15)

#define DEFIO_TAG_E__PF0 DEFIO_TAG (F, 0)
#define DEFIO_TAG_E__PF1 DEFIO_TAG (F, 1)
#define DEFIO_TAG_E__PF2 DEFIO_TAG (F, 2)
#define DEFIO_TAG_E__PF3 DEFIO_TAG (F, 3)
#define DEFIO_TAG_E__PF4 DEFIO_TAG (F, 4)
#define DEFIO_TAG_E__PF5 DEFIO_TAG (F, 5)
#define DEFIO_TAG_E__PF6 DEFIO_TAG (F, 6)
#define DEFIO_TAG_E__PF7 DEFIO_TAG (F, 7)
#define DEFIO_TAG_E__PF8 DEFIO_TAG (F, 8)
#define DEFIO_TAG_E__PF9 DEFIO_TAG (F, 9)
#define DEFIO_TAG_E__PF10 DEFIO_TAG (F, 10)
#define DEFIO_TAG_E__PF11 DEFIO_TAG (F, 11)
#define DEFIO_TAG_E__PF12 DEFIO_TAG (F, 12)
#define DEFIO_TAG_E__PF13 DEFIO_TAG (F, 13)
#define DEFIO_TAG_E__PF14 DEFIO_TAG (F, 14)
#define DEFIO_TAG_E__PF15 DEFIO_TAG (F, 15)

#define DEFIO_TAG_E__PG0 DEFIO_TAG (G, 0)
#define DEFIO_TAG_E__PG1 DEFIO_TAG (G, 1)
#define DEFIO_TAG_E__PG2 DEFIO_TAG (G, 2)
#define DEFIO_TAG_E__PG3 DEFIO_TAG (G, 3)
#define DEFIO_TAG_E__PG4 DEFIO_TAG (G, 4)
#define DEFIO_TAG_E__PG5 DEFIO_TAG (G, 5)
#define DEFIO_TAG_E__PG6 DEFIO_TAG (G, 6)
#define DEFIO_TAG_E__PG7 DEFIO_TAG (G, 7)
#define DEFIO_TAG_E__PG8 DEFIO_TAG (G, 8)
#define DEFIO_TAG_E__PG9 DEFIO_TAG (G, 9)
#define DEFIO_TAG_E__PG10 DEFIO_TAG (G, 10)
#define DEFIO_TAG_E__PG11 DEFIO_TAG (G, 11)
#define DEFIO_TAG_E__PG12 DEFIO_TAG (G, 12)
#define DEFIO_TAG_E__PG13 DEFIO_TAG (G, 13)
#define DEFIO_TAG_E__PG14 DEFIO_TAG (G, 14)
#define DEFIO_TAG_E__PG15 DEFIO_TAG (G, 15)

#define DEFIO_TAG_E__PH0 DEFIO_TAG (H, 0)
#define DEFIO_TAG_E__PH1 DEFIO_TAG (H, 1)
#define DEFIO_TAG_E__PH2 DEFIO_TAG (H, 2)
#define DEFIO_TAG_E__PH3 DEFIO_TAG (H, 3)
#define DEFIO_TAG_E__PH4 DEFIO_TAG (H, 4)
#define DEFIO_TAG_E__PH5 DEFIO_TAG (H, 5)
#define DEFIO_TAG_E__PH6 DEFIO_TAG (H, 6)
#define DEFIO_TAG_E__PH7 DEFIO_TAG (H, 7)
#define DEFIO_TAG_E__PH8 DEFIO_TAG (H, 8)
#define DEFIO_TAG_E__PH9 DEFIO_TAG (H, 9)
#define DEFIO_TAG_E__PH10 DEFIO_TAG (H, 10)
#define DEFIO_TAG_E__PH11 DEFIO_TAG (H, 11)
#define DEFIO_TAG_E__PH12 DEFIO_TAG (H, 12)
#define DEFIO_TAG_E__PH13 DEFIO_TAG (H, 13)
#define DEFIO_TAG_E__PH14 DEFIO_TAG (H, 14)
#define DEFIO_TAG_E__PH15 DEFIO_TAG (H, 15)

#define DEFIO_TAG_E__PI0 DEFIO_TAG (I, 0)
#define DEFIO_TAG_E__PI1 DEFIO_TAG (I, 1)
#define DEFIO_TAG_E__PI2 DEFIO_TAG (I, 2)
#define DEFIO_TAG_E__PI3 DEFIO_TAG (I, 3)
#define DEFIO_TAG_E__PI4 DEFIO_TAG (I, 4)
#define DEFIO_TAG_E__PI5 DEFIO_TAG (I, 5)
#define DEFIO_TAG_E__PI6 DEFIO_TAG (I, 6)
#define DEFIO_TAG_E__PI7 DEFIO_TAG (I, 7)
#define DEFIO_TAG_E__PI8 DEFIO_TAG (I, 8)
#define DEFIO_TAG_E__PI9 DEFIO_TAG (I, 9)
#define DEFIO_TAG_E__PI10 DEFIO_TAG (I, 10)
#define DEFIO_TAG_E__PI11 DEFIO_TAG (I, 11)
#define DEFIO_TAG_E__PI12 DEFIO_TAG (I, 12)
#define DEFIO_TAG_E__PI13 DEFIO_TAG (I, 13)
#define DEFIO_TAG_E__PI14 DEFIO_TAG (I, 14)
#define DEFIO_TAG_E__PI15 DEFIO_TAG (I, 15)

#define DEFIO_TAG_E__PG0 DEFIO_TAG (G, 0)
#define DEFIO_TAG_E__PG1 DEFIO_TAG (G, 1)
#define DEFIO_TAG_E__PG2 DEFIO_TAG (G, 2)
#define DEFIO_TAG_E__PG3 DEFIO_TAG (G, 3)
#define DEFIO_TAG_E__PG4 DEFIO_TAG (G, 4)
#define DEFIO_TAG_E__PG5 DEFIO_TAG (G, 5)
#define DEFIO_TAG_E__PG6 DEFIO_TAG (G, 6)
#define DEFIO_TAG_E__PG7 DEFIO_TAG (G, 7)
#define DEFIO_TAG_E__PG8 DEFIO_TAG (G, 8)
#define DEFIO_TAG_E__PG9 DEFIO_TAG (G, 9)
#define DEFIO_TAG_E__PG10 DEFIO_TAG (G, 10)
#define DEFIO_TAG_E__PG11 DEFIO_TAG (G, 11)
#define DEFIO_TAG_E__PG12 DEFIO_TAG (G, 12)
#define DEFIO_TAG_E__PG13 DEFIO_TAG (G, 13)
#define DEFIO_TAG_E__PG14 DEFIO_TAG (G, 14)
#define DEFIO_TAG_E__PG15 DEFIO_TAG (G, 15)

#define DEFIO_TAG_E__PK0 DEFIO_TAG (K, 0)
#define DEFIO_TAG_E__PK1 DEFIO_TAG (K, 1)
#define DEFIO_TAG_E__PK2 DEFIO_TAG (K, 2)
#define DEFIO_TAG_E__PK3 DEFIO_TAG (K, 3)
#define DEFIO_TAG_E__PK4 DEFIO_TAG (K, 4)
#define DEFIO_TAG_E__PK5 DEFIO_TAG (K, 5)
#define DEFIO_TAG_E__PK6 DEFIO_TAG (K, 6)
#define DEFIO_TAG_E__PK7 DEFIO_TAG (K, 7)
#define DEFIO_TAG_E__PK8 DEFIO_TAG (K, 8)
#define DEFIO_TAG_E__PK9 DEFIO_TAG (K, 9)
#define DEFIO_TAG_E__PK10 DEFIO_TAG (K, 10)
#define DEFIO_TAG_E__PK11 DEFIO_TAG (K, 11)
#define DEFIO_TAG_E__PK12 DEFIO_TAG (K, 12)
#define DEFIO_TAG_E__PK13 DEFIO_TAG (K, 13)
#define DEFIO_TAG_E__PK14 DEFIO_TAG (K, 14)
#define DEFIO_TAG_E__PK15 DEFIO_TAG (K, 15)
